apiVersion: conditionalaccess.azuread.upbound.io/v1beta1
kind: Location
metadata:
  annotations:
    meta.upbound.io/example-id: conditionalaccess/v1beta1/location
  labels:
    testing.upbound.io/example-name: example-ip
  name: example-ip
spec:
  forProvider:
    displayName: IP Named Location
    ip:
    - ipRanges:
      - 1.1.1.1/32
      - 2.2.2.2/32
      trusted: true
