# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ignored
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          path: /convert
      conversionReviewVersions:
      - v1
