apiVersion: invitations.azuread.upbound.io/v1beta1
kind: Invitation
metadata:
  annotations:
    meta.upbound.io/example-id: invitations/v1beta1/invitation
    upjet.upbound.io/manual-intervention: "This resource requires a user with the correct domain"
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    userEmailAddress: testuser@upbound.io
    redirectUrl: https://portal.azure.com
