apiVersion: conditionalaccess.azuread.upbound.io/v1beta1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: conditionalaccess/v1beta1/policy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: example policy
    state: disabled  
    conditions:
    - applications:
      - excludedApplications: []
        includedApplications:
        - All
      clientAppTypes:
      - all
      devices:
      - filter:
        - mode: exclude
          rule: device.operatingSystem eq "Doors"
      locations:
      - excludedLocations:
        - AllTrusted
        includedLocations:
        - All
      platforms:
      - excludedPlatforms:
        - iOS
        includedPlatforms:
        - android
      signInRiskLevels:
      - medium
      userRiskLevels:
      - medium
      users:
      - excludedUsers:
        - GuestsOrExternalUsers
        includedUsers:
        - All
    grantControls:
    - builtInControls:
      - mfa
      operator: OR
    sessionControls:
    - applicationEnforcedRestrictionsEnabled: true
      cloudAppSecurityPolicy: monitorOnly
      signInFrequency: 10
      signInFrequencyPeriod: hours
