// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AccessPackageResourceCatalogAssociationInitParameters struct {

	// The unique ID of the access package catalog. Changing this forces a new resource to be created.
	// The unique ID of the access package catalog
	// +crossplane:generate:reference:type=github.com/upbound/provider-azuread/v2/apis/cluster/identitygovernance/v1beta1.AccessPackageCatalog
	CatalogID *string `json:"catalogId,omitempty" tf:"catalog_id,omitempty"`

	// Reference to a AccessPackageCatalog in identitygovernance to populate catalogId.
	// +kubebuilder:validation:Optional
	CatalogIDRef *v2.Reference `json:"catalogIdRef,omitempty" tf:"-"`

	// Selector for a AccessPackageCatalog in identitygovernance to populate catalogId.
	// +kubebuilder:validation:Optional
	CatalogIDSelector *v2.Selector `json:"catalogIdSelector,omitempty" tf:"-"`

	// The unique identifier of the resource in the origin system. In the case of an Azure AD group, this is the identifier of the group. Changing this forces a new resource to be created.
	// The unique identifier of the resource in the origin system. In the case of an Azure AD group, this is the identifier of the group
	// +crossplane:generate:reference:type=github.com/upbound/provider-azuread/v2/apis/cluster/groups/v1beta2.Group
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("object_id",true)
	ResourceOriginID *string `json:"resourceOriginId,omitempty" tf:"resource_origin_id,omitempty"`

	// Reference to a Group in groups to populate resourceOriginId.
	// +kubebuilder:validation:Optional
	ResourceOriginIDRef *v2.Reference `json:"resourceOriginIdRef,omitempty" tf:"-"`

	// Selector for a Group in groups to populate resourceOriginId.
	// +kubebuilder:validation:Optional
	ResourceOriginIDSelector *v2.Selector `json:"resourceOriginIdSelector,omitempty" tf:"-"`

	// The type of the resource in the origin system, such as SharePointOnline, AadApplication or AadGroup. Changing this forces a new resource to be created.
	// The type of the resource in the origin system, such as SharePointOnline, AadApplication or AadGroup
	ResourceOriginSystem *string `json:"resourceOriginSystem,omitempty" tf:"resource_origin_system,omitempty"`
}

type AccessPackageResourceCatalogAssociationObservation struct {

	// The unique ID of the access package catalog. Changing this forces a new resource to be created.
	// The unique ID of the access package catalog
	CatalogID *string `json:"catalogId,omitempty" tf:"catalog_id,omitempty"`

	// The ID of this resource, the ID is the concatenation of catalog_id and resource_origin_id with colon in between.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The unique identifier of the resource in the origin system. In the case of an Azure AD group, this is the identifier of the group. Changing this forces a new resource to be created.
	// The unique identifier of the resource in the origin system. In the case of an Azure AD group, this is the identifier of the group
	ResourceOriginID *string `json:"resourceOriginId,omitempty" tf:"resource_origin_id,omitempty"`

	// The type of the resource in the origin system, such as SharePointOnline, AadApplication or AadGroup. Changing this forces a new resource to be created.
	// The type of the resource in the origin system, such as SharePointOnline, AadApplication or AadGroup
	ResourceOriginSystem *string `json:"resourceOriginSystem,omitempty" tf:"resource_origin_system,omitempty"`
}

type AccessPackageResourceCatalogAssociationParameters struct {

	// The unique ID of the access package catalog. Changing this forces a new resource to be created.
	// The unique ID of the access package catalog
	// +crossplane:generate:reference:type=github.com/upbound/provider-azuread/v2/apis/cluster/identitygovernance/v1beta1.AccessPackageCatalog
	// +kubebuilder:validation:Optional
	CatalogID *string `json:"catalogId,omitempty" tf:"catalog_id,omitempty"`

	// Reference to a AccessPackageCatalog in identitygovernance to populate catalogId.
	// +kubebuilder:validation:Optional
	CatalogIDRef *v2.Reference `json:"catalogIdRef,omitempty" tf:"-"`

	// Selector for a AccessPackageCatalog in identitygovernance to populate catalogId.
	// +kubebuilder:validation:Optional
	CatalogIDSelector *v2.Selector `json:"catalogIdSelector,omitempty" tf:"-"`

	// The unique identifier of the resource in the origin system. In the case of an Azure AD group, this is the identifier of the group. Changing this forces a new resource to be created.
	// The unique identifier of the resource in the origin system. In the case of an Azure AD group, this is the identifier of the group
	// +crossplane:generate:reference:type=github.com/upbound/provider-azuread/v2/apis/cluster/groups/v1beta2.Group
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("object_id",true)
	// +kubebuilder:validation:Optional
	ResourceOriginID *string `json:"resourceOriginId,omitempty" tf:"resource_origin_id,omitempty"`

	// Reference to a Group in groups to populate resourceOriginId.
	// +kubebuilder:validation:Optional
	ResourceOriginIDRef *v2.Reference `json:"resourceOriginIdRef,omitempty" tf:"-"`

	// Selector for a Group in groups to populate resourceOriginId.
	// +kubebuilder:validation:Optional
	ResourceOriginIDSelector *v2.Selector `json:"resourceOriginIdSelector,omitempty" tf:"-"`

	// The type of the resource in the origin system, such as SharePointOnline, AadApplication or AadGroup. Changing this forces a new resource to be created.
	// The type of the resource in the origin system, such as SharePointOnline, AadApplication or AadGroup
	// +kubebuilder:validation:Optional
	ResourceOriginSystem *string `json:"resourceOriginSystem,omitempty" tf:"resource_origin_system,omitempty"`
}

// AccessPackageResourceCatalogAssociationSpec defines the desired state of AccessPackageResourceCatalogAssociation
type AccessPackageResourceCatalogAssociationSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   AccessPackageResourceCatalogAssociationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccessPackageResourceCatalogAssociationInitParameters `json:"initProvider,omitempty"`
}

// AccessPackageResourceCatalogAssociationStatus defines the observed state of AccessPackageResourceCatalogAssociation.
type AccessPackageResourceCatalogAssociationStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               AccessPackageResourceCatalogAssociationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccessPackageResourceCatalogAssociation is the Schema for the AccessPackageResourceCatalogAssociations API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuread}
type AccessPackageResourceCatalogAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.resourceOriginSystem) || (has(self.initProvider) && has(self.initProvider.resourceOriginSystem))",message="spec.forProvider.resourceOriginSystem is a required parameter"
	Spec   AccessPackageResourceCatalogAssociationSpec   `json:"spec"`
	Status AccessPackageResourceCatalogAssociationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccessPackageResourceCatalogAssociationList contains a list of AccessPackageResourceCatalogAssociations
type AccessPackageResourceCatalogAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccessPackageResourceCatalogAssociation `json:"items"`
}

// Repository type metadata.
var (
	AccessPackageResourceCatalogAssociation_Kind             = "AccessPackageResourceCatalogAssociation"
	AccessPackageResourceCatalogAssociation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccessPackageResourceCatalogAssociation_Kind}.String()
	AccessPackageResourceCatalogAssociation_KindAPIVersion   = AccessPackageResourceCatalogAssociation_Kind + "." + CRDGroupVersion.String()
	AccessPackageResourceCatalogAssociation_GroupVersionKind = CRDGroupVersion.WithKind(AccessPackageResourceCatalogAssociation_Kind)
)

func init() {
	SchemeBuilder.Register(&AccessPackageResourceCatalogAssociation{}, &AccessPackageResourceCatalogAssociationList{})
}
