// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AccessPackageCatalogInitParameters struct {

	// The description of the access package catalog.
	// The description of the access package catalog
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The display name of the access package catalog.
	// The display name of the access package catalog
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Whether the access packages in this catalog can be requested by users outside the tenant.
	// Whether the access packages in this catalog can be requested by users outside the tenant
	ExternallyVisible *bool `json:"externallyVisible,omitempty" tf:"externally_visible,omitempty"`

	// Whether the access packages in this catalog are available for management.
	// Whether the access packages in this catalog are available for management
	Published *bool `json:"published,omitempty" tf:"published,omitempty"`
}

type AccessPackageCatalogObservation struct {

	// The description of the access package catalog.
	// The description of the access package catalog
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The display name of the access package catalog.
	// The display name of the access package catalog
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Whether the access packages in this catalog can be requested by users outside the tenant.
	// Whether the access packages in this catalog can be requested by users outside the tenant
	ExternallyVisible *bool `json:"externallyVisible,omitempty" tf:"externally_visible,omitempty"`

	// The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Whether the access packages in this catalog are available for management.
	// Whether the access packages in this catalog are available for management
	Published *bool `json:"published,omitempty" tf:"published,omitempty"`
}

type AccessPackageCatalogParameters struct {

	// The description of the access package catalog.
	// The description of the access package catalog
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The display name of the access package catalog.
	// The display name of the access package catalog
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Whether the access packages in this catalog can be requested by users outside the tenant.
	// Whether the access packages in this catalog can be requested by users outside the tenant
	// +kubebuilder:validation:Optional
	ExternallyVisible *bool `json:"externallyVisible,omitempty" tf:"externally_visible,omitempty"`

	// Whether the access packages in this catalog are available for management.
	// Whether the access packages in this catalog are available for management
	// +kubebuilder:validation:Optional
	Published *bool `json:"published,omitempty" tf:"published,omitempty"`
}

// AccessPackageCatalogSpec defines the desired state of AccessPackageCatalog
type AccessPackageCatalogSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   AccessPackageCatalogParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccessPackageCatalogInitParameters `json:"initProvider,omitempty"`
}

// AccessPackageCatalogStatus defines the observed state of AccessPackageCatalog.
type AccessPackageCatalogStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               AccessPackageCatalogObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccessPackageCatalog is the Schema for the AccessPackageCatalogs API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuread}
type AccessPackageCatalog struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.description) || (has(self.initProvider) && has(self.initProvider.description))",message="spec.forProvider.description is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	Spec   AccessPackageCatalogSpec   `json:"spec"`
	Status AccessPackageCatalogStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccessPackageCatalogList contains a list of AccessPackageCatalogs
type AccessPackageCatalogList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccessPackageCatalog `json:"items"`
}

// Repository type metadata.
var (
	AccessPackageCatalog_Kind             = "AccessPackageCatalog"
	AccessPackageCatalog_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccessPackageCatalog_Kind}.String()
	AccessPackageCatalog_KindAPIVersion   = AccessPackageCatalog_Kind + "." + CRDGroupVersion.String()
	AccessPackageCatalog_GroupVersionKind = CRDGroupVersion.WithKind(AccessPackageCatalog_Kind)
)

func init() {
	SchemeBuilder.Register(&AccessPackageCatalog{}, &AccessPackageCatalogList{})
}
