# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: synchronization.azuread.upbound.io/v1beta1
kind: Job
metadata:
  annotations:
    meta.upbound.io/example-id: synchronization/v1beta1/job
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    enabled: true
    servicePrincipalIdSelector:
      matchLabels:
        testing.upbound.io/example-name: azuread_service_principal
    templateId: dataBricks

---

apiVersion: synchronization.azuread.upbound.io/v1beta1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: synchronization/v1beta1/job
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    credential:
    - key: BaseAddress
      valueSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
    - key: SecretToken
      valueSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
    servicePrincipalIdSelector:
      matchLabels:
        testing.upbound.io/example-name: azuread_service_principal
