/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PrincipalClaimsMappingPolicyAssignmentObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type PrincipalClaimsMappingPolicyAssignmentParameters struct {

	// ID of the claims mapping policy to assign
	// +crossplane:generate:reference:type=github.com/upbound/provider-azuread/apis/policies/v1alpha1.MappingPolicy
	// +kubebuilder:validation:Optional
	ClaimsMappingPolicyID *string `json:"claimsMappingPolicyId,omitempty" tf:"claims_mapping_policy_id,omitempty"`

	// Reference to a MappingPolicy in policies to populate claimsMappingPolicyId.
	// +kubebuilder:validation:Optional
	ClaimsMappingPolicyIDRef *v1.Reference `json:"claimsMappingPolicyIdRef,omitempty" tf:"-"`

	// Selector for a MappingPolicy in policies to populate claimsMappingPolicyId.
	// +kubebuilder:validation:Optional
	ClaimsMappingPolicyIDSelector *v1.Selector `json:"claimsMappingPolicyIdSelector,omitempty" tf:"-"`

	// Object ID of the service principal for which to assign the policy
	// +crossplane:generate:reference:type=Principal
	// +kubebuilder:validation:Optional
	ServicePrincipalID *string `json:"servicePrincipalId,omitempty" tf:"service_principal_id,omitempty"`

	// Reference to a Principal to populate servicePrincipalId.
	// +kubebuilder:validation:Optional
	ServicePrincipalIDRef *v1.Reference `json:"servicePrincipalIdRef,omitempty" tf:"-"`

	// Selector for a Principal to populate servicePrincipalId.
	// +kubebuilder:validation:Optional
	ServicePrincipalIDSelector *v1.Selector `json:"servicePrincipalIdSelector,omitempty" tf:"-"`
}

// PrincipalClaimsMappingPolicyAssignmentSpec defines the desired state of PrincipalClaimsMappingPolicyAssignment
type PrincipalClaimsMappingPolicyAssignmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PrincipalClaimsMappingPolicyAssignmentParameters `json:"forProvider"`
}

// PrincipalClaimsMappingPolicyAssignmentStatus defines the observed state of PrincipalClaimsMappingPolicyAssignment.
type PrincipalClaimsMappingPolicyAssignmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PrincipalClaimsMappingPolicyAssignmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// PrincipalClaimsMappingPolicyAssignment is the Schema for the PrincipalClaimsMappingPolicyAssignments API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuread}
type PrincipalClaimsMappingPolicyAssignment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              PrincipalClaimsMappingPolicyAssignmentSpec   `json:"spec"`
	Status            PrincipalClaimsMappingPolicyAssignmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PrincipalClaimsMappingPolicyAssignmentList contains a list of PrincipalClaimsMappingPolicyAssignments
type PrincipalClaimsMappingPolicyAssignmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PrincipalClaimsMappingPolicyAssignment `json:"items"`
}

// Repository type metadata.
var (
	PrincipalClaimsMappingPolicyAssignment_Kind             = "PrincipalClaimsMappingPolicyAssignment"
	PrincipalClaimsMappingPolicyAssignment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PrincipalClaimsMappingPolicyAssignment_Kind}.String()
	PrincipalClaimsMappingPolicyAssignment_KindAPIVersion   = PrincipalClaimsMappingPolicyAssignment_Kind + "." + CRDGroupVersion.String()
	PrincipalClaimsMappingPolicyAssignment_GroupVersionKind = CRDGroupVersion.WithKind(PrincipalClaimsMappingPolicyAssignment_Kind)
)

func init() {
	SchemeBuilder.Register(&PrincipalClaimsMappingPolicyAssignment{}, &PrincipalClaimsMappingPolicyAssignmentList{})
}
