// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by angryjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	v1beta2 "github.com/upbound/provider-azuread/v2/apis/cluster/serviceprincipals/v1beta2"
	v1beta1 "github.com/upbound/provider-azuread/v2/apis/cluster/users/v1beta1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this PermissionGrant.
func (mg *PermissionGrant) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ResourceServicePrincipalObjectID),
		Extract:      resource.ExtractParamPath("object_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ResourceServicePrincipalObjectIDRef,
		Selector:     mg.Spec.ForProvider.ResourceServicePrincipalObjectIDSelector,
		To: reference.To{
			List:    &v1beta2.PrincipalList{},
			Managed: &v1beta2.Principal{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ResourceServicePrincipalObjectID")
	}
	mg.Spec.ForProvider.ResourceServicePrincipalObjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ResourceServicePrincipalObjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ServicePrincipalObjectID),
		Extract:      resource.ExtractParamPath("object_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ServicePrincipalObjectIDRef,
		Selector:     mg.Spec.ForProvider.ServicePrincipalObjectIDSelector,
		To: reference.To{
			List:    &v1beta2.PrincipalList{},
			Managed: &v1beta2.Principal{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServicePrincipalObjectID")
	}
	mg.Spec.ForProvider.ServicePrincipalObjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ServicePrincipalObjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.UserObjectID),
		Extract:      resource.ExtractParamPath("object_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.UserObjectIDRef,
		Selector:     mg.Spec.ForProvider.UserObjectIDSelector,
		To: reference.To{
			List:    &v1beta1.UserList{},
			Managed: &v1beta1.User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.UserObjectID")
	}
	mg.Spec.ForProvider.UserObjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.UserObjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ResourceServicePrincipalObjectID),
		Extract:      resource.ExtractParamPath("object_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ResourceServicePrincipalObjectIDRef,
		Selector:     mg.Spec.InitProvider.ResourceServicePrincipalObjectIDSelector,
		To: reference.To{
			List:    &v1beta2.PrincipalList{},
			Managed: &v1beta2.Principal{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ResourceServicePrincipalObjectID")
	}
	mg.Spec.InitProvider.ResourceServicePrincipalObjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ResourceServicePrincipalObjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ServicePrincipalObjectID),
		Extract:      resource.ExtractParamPath("object_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ServicePrincipalObjectIDRef,
		Selector:     mg.Spec.InitProvider.ServicePrincipalObjectIDSelector,
		To: reference.To{
			List:    &v1beta2.PrincipalList{},
			Managed: &v1beta2.Principal{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ServicePrincipalObjectID")
	}
	mg.Spec.InitProvider.ServicePrincipalObjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ServicePrincipalObjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.UserObjectID),
		Extract:      resource.ExtractParamPath("object_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.UserObjectIDRef,
		Selector:     mg.Spec.InitProvider.UserObjectIDSelector,
		To: reference.To{
			List:    &v1beta1.UserList{},
			Managed: &v1beta1.User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.UserObjectID")
	}
	mg.Spec.InitProvider.UserObjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.UserObjectIDRef = rsp.ResolvedReference

	return nil
}
