# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: invitations.azuread.upbound.io/v1beta2
kind: Invitation
metadata:
  annotations:
    meta.upbound.io/example-id: invitations/v1beta2/invitation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    redirectUrl: https://portal.azure.com
    userEmailAddress: jdoe@hashicorp.com
