# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: directoryroles.azuread.upbound.io/v1beta1
kind: RoleEligibilityScheduleRequest
metadata:
  annotations:
    meta.upbound.io/example-id: directoryroles/v1beta1/roleeligibilityschedulerequest
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    directoryScopeId: /
    justification: Example
    principalIdSelector:
      matchLabels:
        testing.upbound.io/example-name: azuread_user
    roleDefinitionIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: directoryroles.azuread.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: directoryroles/v1beta1/roleeligibilityschedulerequest
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: Application Administrator
