# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: identitygovernance.azuread.m.upbound.io/v1beta1
kind: PrivilegedAccessGroupEligibilitySchedule
metadata:
  annotations:
    meta.upbound.io/example-id: identitygovernance/v1beta1/privilegedaccessgroupeligibilityschedule
  labels:
    testing.upbound.io/example-name: privilegedaccessgroupeligibilityschedule
  name: privilegedaccessgroupeligibilityschedule
  namespace: upbound-system
spec:
  forProvider:
    assignmentType: member
    duration: P30D
    groupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: privilegedaccessgroupeligibilityschedule-pim
    justification: as requested
    principalIdSelector:
      matchLabels:
        testing.upbound.io/example-name: privilegedaccessgroupeligibilityschedule-member
---
apiVersion: groups.azuread.m.upbound.io/v1beta1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: identitygovernance/v1beta1/privilegedaccessgroupeligibilityschedule
    uptest.upbound.io/pre-delete-hook: ../testhooks/delete-privilegedaccessgroupeligibilityschedule.sh
  labels:
    testing.upbound.io/example-name: privilegedaccessgroupeligibilityschedule-pim
  name: privilegedaccessgroupeligibilityschedule
  namespace: upbound-system
spec:
  forProvider:
    displayName: privilegedaccessgroupeligibilityschedule
    securityEnabled: true
---
apiVersion: users.azuread.m.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: identitygovernance/v1beta1/privilegedaccessgroupeligibilityschedule
    uptest.upbound.io/pre-delete-hook: ../testhooks/delete-privilegedaccessgroupeligibilityschedule.sh
  labels:
    testing.upbound.io/example-name: privilegedaccessgroupeligibilityschedule-member
  name: privilegedaccessgroupeligibilityschedule
  namespace: upbound-system
spec:
  forProvider:
    displayName: privilegedaccessgroupeligibilityschedule
    mailNickname: privilegedaccessgroupeligibilityschedule
    passwordSecretRef:
      key: credentials
      name: privilegedaccessgroupeligibilityschedule
    userPrincipalName: privilegedaccessgroupeligibilityschedule@devopsupbound.onmicrosoft.com
---
apiVersion: v1
kind: Secret
metadata:
  name: privilegedaccessgroupeligibilityschedule
  namespace: upbound-system
type: Opaque
stringData:
  credentials: SecretP@sswd99!
