apiVersion: serviceprincipaldelegated.azuread.upbound.io/v1beta1
kind: PermissionGrant
metadata:
  annotations:
    meta.upbound.io/example-id: serviceprincipaldelegated/v1beta1/permissiongrant
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    servicePrincipalObjectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    resourceServicePrincipalObjectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: msgraph
    claimValues:
        # Id obtained from status.atProvider.oauth2PermissionScopeIds["openid"] from the Principal(msgraph) resource below.
      - 37f7f235-527c-4136-accd-4a02d197296e
        # Id obtained from status.atProvider.oauth2PermissionScopeIds["User.Read.All"] from the Principal(msgraph) resource below.
      - a154be20-db9c-4678-8ab7-66f6cc099a59
---
apiVersion: serviceprincipals.azuread.upbound.io/v1beta1
kind: Principal
metadata:
  annotations:
    meta.upbound.io/example-id: serviceprincipaldelegated/v1beta1/permissiongrant
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applicationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
---
apiVersion: applications.azuread.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: serviceprincipaldelegated/v1beta1/permissiongrant
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: example
    requiredResourceAccess:
        # # I got this id from "data.azuread_application_published_app_ids.well_known.result.MicrosoftGraph"
      - resourceAppId: 00000003-0000-0000-c000-000000000000
        resourceAccess:
            # Id obtained from status.atProvider.oauth2PermissionScopeIds["openid"] from the Principal(msgraph) resource below.
          - id: 37f7f235-527c-4136-accd-4a02d197296e
            type: Scope
            # Id obtained from status.atProvider.oauth2PermissionScopeIds["User.Read"] from the Principal(msgraph) resource below.
          - id: e1fe6dd8-ba31-4d61-89e7-88639da4683d
            type: Scope
---
apiVersion: serviceprincipals.azuread.upbound.io/v1beta1
kind: Principal
metadata:
  annotations:
    meta.upbound.io/example-id: serviceprincipaldelegated/v1beta1/permissiongrant
  labels:
    testing.upbound.io/example-name: msgraph
  name: msgraph
spec:
  forProvider:
    # # I got this id from "data.azuread_application_published_app_ids.well_known.result.MicrosoftGraph"
    applicationId: 00000003-0000-0000-c000-000000000000
    useExisting: true
