# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: serviceprincipals.azuread.upbound.io/v1beta2
kind: Principal
metadata:
  annotations:
    meta.upbound.io/example-id: serviceprincipals/v1beta1/principal
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clientIdIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    appRoleAssignmentRequired: false
---
apiVersion: applications.azuread.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: serviceprincipals/v1beta1/principal
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: example
