apiVersion: directoryroles.azuread.upbound.io/v1beta1
kind: RoleMember
metadata:
  annotations:
    meta.upbound.io/example-id: directoryroles/v1beta1/rolemember
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    roleObjectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    memberObjectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
---
apiVersion: directoryroles.azuread.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: directoryroles/v1beta1/rolemember
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: Security administrator
---
apiVersion: users.azuread.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: directoryroles/v1beta1/rolemember
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    userPrincipalName: testuser_upbound.io#EXT#@devopsupbound.onmicrosoft.com
    displayName: testuser
    passwordSecretRef:
      key: credentials
      name: example-secret
      namespace: upbound-system
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: upbound-system
type: Opaque
stringData: 
  credentials: SecretP@sswd99!