apiVersion: identitygovernance.azuread.m.upbound.io/v1beta1
kind: PrivilegedAccessGroupAssignmentSchedule
metadata:
  annotations:
    meta.upbound.io/example-id: identitygovernance/v1beta1/privilegedaccessgroupassignmentschedule
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    assignmentType: member
    duration: P30D
    groupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: pim
    justification: as requested
    principalIdSelector:
      matchLabels:
        testing.upbound.io/example-name: member

---

apiVersion: groups.azuread.m.upbound.io/v1beta1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: identitygovernance/v1beta1/privilegedaccessgroupassignmentschedule
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    displayName: group-name
    securityEnabled: true

---

apiVersion: users.azuread.m.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: identitygovernance/v1beta1/privilegedaccessgroupassignmentschedule
  labels:
    testing.upbound.io/example-name: member
  name: member
  namespace: upbound-system
spec:
  forProvider:
    displayName: J. Doe
    mailNickname: jdoe
    passwordSecretRef:
      key: example-key
      name: example-secret
    userPrincipalName: jdoe@hashicorp.com
