apiVersion: groups.azuread.upbound.io/v1beta1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: groups/v1beta1/group
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: example
    securityEnabled: true