apiVersion: groups.azuread.upbound.io/v1alpha1
kind: Member
metadata:
  annotations:
    meta.upbound.io/example-id: groups/v1beta1/member
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    groupObjectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    memberObjectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
---
apiVersion: groups.azuread.upbound.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: groups/v1beta1/member
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: example
    securityEnabled: true
---
apiVersion: users.azuread.upbound.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: users/v1beta1/member
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    userPrincipalName: testuser_upbound.io#EXT#@devopsupbound.onmicrosoft.com
    displayName: testuser
    passwordSecretRef:
      key: credentials
      name: example-secret
      namespace: upbound-system
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: upbound-system
type: Opaque
stringData: 
  credentials: SecretP@sswd99!