apiVersion: serviceprincipals.azuread.upbound.io/v1alpha1
kind: MappingPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: applications/v1beta1/mappingpolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: My Policy
    definition:
    - |-
      {
        "ClaimsMappingPolicy": {
          "ClaimsSchema": [
            {
              "ID"            : "employeeid",
              "JwtClaimType"  : "name",
              "SamlClaimType" : "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name",
              "Source"        : "user"
            },
            {
              "ID"            : "tenantcountry",
              "JwtClaimType"  : "country",
              "SamlClaimType" : "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/country",
              "Source"        : "company"
            }
          ],
          "IncludeBasicClaimSet" : "true",
          "Version"              : 1
        }
      }
