apiVersion: serviceprincipals.azuread.upbound.io/v1alpha1
kind: Principal
metadata:
  annotations:
    meta.upbound.io/example-id: applications/v1beta1/principal
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applicationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    appRoleAssignmentRequired: false
---
apiVersion: applications.azuread.upbound.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: applications/v1beta1/principal
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: example
