apiVersion: serviceprincipals.azuread.upbound.io/v1beta2
kind: Principal
metadata:
  annotations:
    meta.upbound.io/example-id: serviceprincipals/v1beta2/principal
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    appRoleAssignmentRequired: false
    clientIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    owners:
    - ${data.azuread_client_config.current.object_id}

---

apiVersion: applications.azuread.upbound.io/v1beta2
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: serviceprincipals/v1beta2/principal
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: example
    owners:
    - ${data.azuread_client_config.current.object_id}
