apiVersion: privileged.azuread.upbound.io/v1beta1
kind: AccessGroupAssignmentSchedule
metadata:
  annotations:
    meta.upbound.io/example-id: privileged/v1beta1/accessgroupassignmentschedule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    assignmentType: member
    duration: P30D
    groupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: pim
    justification: as requested
    principalIdSelector:
      matchLabels:
        testing.upbound.io/example-name: member

---

apiVersion: groups.azuread.upbound.io/v1beta2
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: privileged/v1beta1/accessgroupassignmentschedule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: group-name
    securityEnabled: true

---

apiVersion: users.azuread.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: privileged/v1beta1/accessgroupassignmentschedule
  labels:
    testing.upbound.io/example-name: member
  name: member
spec:
  forProvider:
    displayName: J. Doe
    mailNickname: jdoe
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    userPrincipalName: jdoe@hashicorp.com
