/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Member.
func (mg *Member) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AdministrativeUnitObjectID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.AdministrativeUnitObjectIDRef,
		Selector:     mg.Spec.ForProvider.AdministrativeUnitObjectIDSelector,
		To: reference.To{
			List:    &UnitList{},
			Managed: &Unit{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AdministrativeUnitObjectID")
	}
	mg.Spec.ForProvider.AdministrativeUnitObjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AdministrativeUnitObjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.AdministrativeUnitObjectID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.AdministrativeUnitObjectIDRef,
		Selector:     mg.Spec.InitProvider.AdministrativeUnitObjectIDSelector,
		To: reference.To{
			List:    &UnitList{},
			Managed: &Unit{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.AdministrativeUnitObjectID")
	}
	mg.Spec.InitProvider.AdministrativeUnitObjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AdministrativeUnitObjectIDRef = rsp.ResolvedReference

	return nil
}
