apiVersion: serviceprincipals.azuread.upbound.io/v1beta1
kind: Principal
metadata:
  annotations:
    meta.upbound.io/example-id: serviceprincipals/v1beta1/principal
  labels:
    testing.upbound.io/example-name: msgraph
  name: msgraph
spec:
  forProvider:
    applicationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: azuread_application_published_app_ids
    useExisting: true

---

apiVersion: applications.azuread.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: serviceprincipals/v1beta1/principal
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: example
    requiredResourceAccess:
    - resourceAccess:
      - id: ${azuread_service_principal.msgraph.oauth2_permission_scope_ids["openid"]}
        type: Scope
      - id: ${azuread_service_principal.msgraph.oauth2_permission_scope_ids["User.Read"]}
        type: Scope
      resourceAppId: ${data.azuread_application_published_app_ids.well_known.result.MicrosoftGraph}

---

