# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: synchronization.azuread.upbound.io/v1beta1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: synchronization/v1beta1/secret
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    servicePrincipalIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    credential:
      - key: BaseAddress
        valueSecretRef:
          key: BaseAddress
          name: example-secret
          namespace: upbound-system
      - key: SecretToken
        valueSecretRef:
          key: SecretToken
          name: example-secret
          namespace: upbound-system
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: upbound-system
type: Opaque
stringData:
  BaseAddress: abc
  SecretToken: some-token
---
apiVersion: serviceprincipals.azuread.upbound.io/v1beta1
kind: Principal
metadata:
  annotations:
    meta.upbound.io/example-id: synchronization/v1beta1/secret
    uptest.upbound.io/pre-delete-hook: ../testhooks/delete-secret.sh
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clientIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    useExisting: true
---
apiVersion: applications.azuread.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: synchronization/v1beta1/secret
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    # I got this template_id using `display_name = "Azure Databricks SCIM Provisioning Connector"` in azuread_application_template data.
    templateId: 9c9818d2-2900-49e8-8ba4-22688be7c675
    displayName: example
    featureTags:
      - enterprise: true
        gallery: true
