# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: conditionalaccess.azuread.m.upbound.io/v1beta1
kind: AccessPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: conditionalaccess/v1beta1/accesspolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    conditions:
      applications:
        excludedApplications: []
        includedApplications:
        - All
      clientAppTypes:
      - all
      devices:
        filter:
          mode: exclude
          rule: device.operatingSystem eq "Doors"
      locations:
        excludedLocations:
        - AllTrusted
        includedLocations:
        - All
      platforms:
        excludedPlatforms:
        - iOS
        includedPlatforms:
        - android
      signInRiskLevels:
      - medium
      userRiskLevels:
      - medium
      users:
        excludedUsers:
        - GuestsOrExternalUsers
        includedUsers:
        - All
    displayName: example policy
    grantControls:
      builtInControls:
      - mfa
      operator: OR
    sessionControls:
      applicationEnforcedRestrictionsEnabled: true
      cloudAppSecurityPolicy: monitorOnly
      disableResilienceDefaults: false
      signInFrequency: 10
      signInFrequencyPeriod: hours
    state: disabled
