apiVersion: synchronization.azuread.m.upbound.io/v1beta1
kind: Job
metadata:
  annotations:
    meta.upbound.io/example-id: synchronization/v1beta1/job
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    enabled: true
    servicePrincipalIdSelector:
      matchLabels:
        testing.upbound.io/example-name: azuread_service_principal
    templateId: dataBricks

---

apiVersion: synchronization.azuread.m.upbound.io/v1beta1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: synchronization/v1beta1/job
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    credential:
    - key: BaseAddress
      valueSecretRef:
        key: example-key
        name: example-secret
    - key: SecretToken
      valueSecretRef:
        key: example-key
        name: example-secret
    servicePrincipalIdSelector:
      matchLabels:
        testing.upbound.io/example-name: azuread_service_principal
