apiVersion: synchronization.azuread.m.upbound.io/v1beta1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: synchronization/v1beta1/secret
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    credential:
    - key: BaseAddress
      valueSecretRef:
        key: example-key
        name: example-secret
    - key: SecretToken
      valueSecretRef:
        key: example-key
        name: example-secret
    servicePrincipalIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: applications.azuread.m.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: synchronization/v1beta1/secret
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    displayName: example
    featureTags:
    - enterprise: true
      gallery: true
    templateId: ${data.azuread_application_template.example.template_id}

---

apiVersion: serviceprincipals.azuread.m.upbound.io/v1beta1
kind: Principal
metadata:
  annotations:
    meta.upbound.io/example-id: synchronization/v1beta1/secret
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    clientIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    useExisting: true
