# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: synchronization.azuread.m.upbound.io/v1beta1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: synchronization/v1beta1/secret
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    credential:
    - key: BaseAddress
      valueSecretRef:
        key: example-key
        name: example-secret
    - key: SecretToken
      valueSecretRef:
        key: example-key
        name: example-secret
    servicePrincipalIdSelector:
      matchLabels:
        testing.upbound.io/example-name: azuread_service_principal
