apiVersion: applications.azuread.upbound.io/v1beta1
kind: PreAuthorized
metadata:
  annotations:
    meta.upbound.io/example-id: applications/v1beta1/preauthorized
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applicationObjectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: authorizer
    authorizedAppIdSelector:
      matchLabels:
        testing.upbound.io/example-name: authorized
    permissionIds:
    - ced9c4c3-c273-4f0f-ac71-a20377b90f9c
    - 2d5e07ca-664d-4d9b-ad61-ec07fd215213

---

apiVersion: applications.azuread.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: applications/v1beta1/preauthorized
  labels:
    testing.upbound.io/example-name: authorized
  name: authorized
spec:
  forProvider:
    displayName: example-authorized-app

---

apiVersion: applications.azuread.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: applications/v1beta1/preauthorized
  labels:
    testing.upbound.io/example-name: authorizer
  name: authorizer
spec:
  forProvider:
    api:
    - oauth2PermissionScope:
      - adminConsentDescription: Administer the application
        adminConsentDisplayName: Administer
        enabled: true
        id: ced9c4c3-c273-4f0f-ac71-a20377b90f9c
        type: Admin
        value: administer
      - adminConsentDescription: Access the application
        adminConsentDisplayName: Access
        enabled: true
        id: 2d5e07ca-664d-4d9b-ad61-ec07fd215213
        type: User
        userConsentDescription: Access the application
        userConsentDisplayName: Access
        value: user_impersonation
    displayName: example-authorizing-app
