// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AccessPackageResourcePackageAssociationInitParameters struct {

	// The ID of access package this resource association is configured to. Changing this forces a new resource to be created.
	// The ID of access package this resource association is configured to
	// +crossplane:generate:reference:type=github.com/upbound/provider-azuread/v2/apis/namespaced/identitygovernance/v1beta1.AccessPackage
	AccessPackageID *string `json:"accessPackageId,omitempty" tf:"access_package_id,omitempty"`

	// Reference to a AccessPackage in identitygovernance to populate accessPackageId.
	// +kubebuilder:validation:Optional
	AccessPackageIDRef *v2.NamespacedReference `json:"accessPackageIdRef,omitempty" tf:"-"`

	// Selector for a AccessPackage in identitygovernance to populate accessPackageId.
	// +kubebuilder:validation:Optional
	AccessPackageIDSelector *v2.NamespacedSelector `json:"accessPackageIdSelector,omitempty" tf:"-"`

	// The role of access type to the specified resource. Valid values are Member, or Owner The default is Member. Changing this forces a new resource to be created.
	// The role of access type to the specified resource, valid values are `Member` and `Owner`
	AccessType *string `json:"accessType,omitempty" tf:"access_type,omitempty"`

	// The ID of the catalog association from the azuread_access_package_resource_catalog_association resource. Changing this forces a new resource to be created.
	// The ID of the access package catalog association
	// +crossplane:generate:reference:type=github.com/upbound/provider-azuread/v2/apis/namespaced/identitygovernance/v1beta1.AccessPackageResourceCatalogAssociation
	CatalogResourceAssociationID *string `json:"catalogResourceAssociationId,omitempty" tf:"catalog_resource_association_id,omitempty"`

	// Reference to a AccessPackageResourceCatalogAssociation in identitygovernance to populate catalogResourceAssociationId.
	// +kubebuilder:validation:Optional
	CatalogResourceAssociationIDRef *v2.NamespacedReference `json:"catalogResourceAssociationIdRef,omitempty" tf:"-"`

	// Selector for a AccessPackageResourceCatalogAssociation in identitygovernance to populate catalogResourceAssociationId.
	// +kubebuilder:validation:Optional
	CatalogResourceAssociationIDSelector *v2.NamespacedSelector `json:"catalogResourceAssociationIdSelector,omitempty" tf:"-"`
}

type AccessPackageResourcePackageAssociationObservation struct {

	// The ID of access package this resource association is configured to. Changing this forces a new resource to be created.
	// The ID of access package this resource association is configured to
	AccessPackageID *string `json:"accessPackageId,omitempty" tf:"access_package_id,omitempty"`

	// The role of access type to the specified resource. Valid values are Member, or Owner The default is Member. Changing this forces a new resource to be created.
	// The role of access type to the specified resource, valid values are `Member` and `Owner`
	AccessType *string `json:"accessType,omitempty" tf:"access_type,omitempty"`

	// The ID of the catalog association from the azuread_access_package_resource_catalog_association resource. Changing this forces a new resource to be created.
	// The ID of the access package catalog association
	CatalogResourceAssociationID *string `json:"catalogResourceAssociationId,omitempty" tf:"catalog_resource_association_id,omitempty"`

	// The ID of this resource. The ID is combined by four fields with colon in between, the four fields are access_package_id, this package association id, resource_origin_id and access_type.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type AccessPackageResourcePackageAssociationParameters struct {

	// The ID of access package this resource association is configured to. Changing this forces a new resource to be created.
	// The ID of access package this resource association is configured to
	// +crossplane:generate:reference:type=github.com/upbound/provider-azuread/v2/apis/namespaced/identitygovernance/v1beta1.AccessPackage
	// +kubebuilder:validation:Optional
	AccessPackageID *string `json:"accessPackageId,omitempty" tf:"access_package_id,omitempty"`

	// Reference to a AccessPackage in identitygovernance to populate accessPackageId.
	// +kubebuilder:validation:Optional
	AccessPackageIDRef *v2.NamespacedReference `json:"accessPackageIdRef,omitempty" tf:"-"`

	// Selector for a AccessPackage in identitygovernance to populate accessPackageId.
	// +kubebuilder:validation:Optional
	AccessPackageIDSelector *v2.NamespacedSelector `json:"accessPackageIdSelector,omitempty" tf:"-"`

	// The role of access type to the specified resource. Valid values are Member, or Owner The default is Member. Changing this forces a new resource to be created.
	// The role of access type to the specified resource, valid values are `Member` and `Owner`
	// +kubebuilder:validation:Optional
	AccessType *string `json:"accessType,omitempty" tf:"access_type,omitempty"`

	// The ID of the catalog association from the azuread_access_package_resource_catalog_association resource. Changing this forces a new resource to be created.
	// The ID of the access package catalog association
	// +crossplane:generate:reference:type=github.com/upbound/provider-azuread/v2/apis/namespaced/identitygovernance/v1beta1.AccessPackageResourceCatalogAssociation
	// +kubebuilder:validation:Optional
	CatalogResourceAssociationID *string `json:"catalogResourceAssociationId,omitempty" tf:"catalog_resource_association_id,omitempty"`

	// Reference to a AccessPackageResourceCatalogAssociation in identitygovernance to populate catalogResourceAssociationId.
	// +kubebuilder:validation:Optional
	CatalogResourceAssociationIDRef *v2.NamespacedReference `json:"catalogResourceAssociationIdRef,omitempty" tf:"-"`

	// Selector for a AccessPackageResourceCatalogAssociation in identitygovernance to populate catalogResourceAssociationId.
	// +kubebuilder:validation:Optional
	CatalogResourceAssociationIDSelector *v2.NamespacedSelector `json:"catalogResourceAssociationIdSelector,omitempty" tf:"-"`
}

// AccessPackageResourcePackageAssociationSpec defines the desired state of AccessPackageResourcePackageAssociation
type AccessPackageResourcePackageAssociationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AccessPackageResourcePackageAssociationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccessPackageResourcePackageAssociationInitParameters `json:"initProvider,omitempty"`
}

// AccessPackageResourcePackageAssociationStatus defines the observed state of AccessPackageResourcePackageAssociation.
type AccessPackageResourcePackageAssociationStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               AccessPackageResourcePackageAssociationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccessPackageResourcePackageAssociation is the Schema for the AccessPackageResourcePackageAssociations API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,azuread}
type AccessPackageResourcePackageAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AccessPackageResourcePackageAssociationSpec   `json:"spec"`
	Status            AccessPackageResourcePackageAssociationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccessPackageResourcePackageAssociationList contains a list of AccessPackageResourcePackageAssociations
type AccessPackageResourcePackageAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccessPackageResourcePackageAssociation `json:"items"`
}

// Repository type metadata.
var (
	AccessPackageResourcePackageAssociation_Kind             = "AccessPackageResourcePackageAssociation"
	AccessPackageResourcePackageAssociation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccessPackageResourcePackageAssociation_Kind}.String()
	AccessPackageResourcePackageAssociation_KindAPIVersion   = AccessPackageResourcePackageAssociation_Kind + "." + CRDGroupVersion.String()
	AccessPackageResourcePackageAssociation_GroupVersionKind = CRDGroupVersion.WithKind(AccessPackageResourcePackageAssociation_Kind)
)

func init() {
	SchemeBuilder.Register(&AccessPackageResourcePackageAssociation{}, &AccessPackageResourcePackageAssociationList{})
}
