# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: applications.azuread.m.upbound.io/v1beta1
kind: AppRole
metadata:
  annotations:
    meta.upbound.io/example-id: applications/v1beta1/approle
  labels:
    testing.upbound.io/example-name: example_administer
  name: example-administer
  namespace: upbound-system
spec:
  forProvider:
    allowedMemberTypes:
      - User
    applicationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    description: My role description
    displayName: Administer
    roleId: f47ac10b-58cc-4372-a567-0e02b2c3d479
    value: admin
---
apiVersion: applications.azuread.m.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: applications/v1beta1/application
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    displayName: example-${Rand.RFC1123Subdomain}
