# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: accesspackages.azuread.upbound.io/v1beta1
kind: AccessPackageResourcePackageAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: accesspackages/v1beta1/accesspackageresourcepackageassociation
  labels:
    testing.upbound.io/example-name: accesspackageresourcepackageassociation
  name: accesspackageresourcepackageassociation
spec:
  forProvider:
    accessPackageIdSelector:
      matchLabels:
        testing.upbound.io/example-name: accesspackage
    catalogResourceAssociationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: accesspackageresourcecatalogassociation

---

apiVersion: accesspackages.azuread.upbound.io/v1beta1
kind: AccessPackage
metadata:
  annotations:
    meta.upbound.io/example-id: accesspackages/v1beta1/accesspackageresourcepackageassociation
  labels:
    testing.upbound.io/example-name: accesspackage
  name: resourcepackageassociation-package
spec:
  forProvider:
    catalogIdSelector:
      matchLabels:
        testing.upbound.io/example-name: accesspackagecatalog
    displayName: example-access-package
    description: Example access package

---

apiVersion: accesspackages.azuread.upbound.io/v1beta1
kind: AccessPackageCatalog
metadata:
  annotations:
    meta.upbound.io/example-id: accesspackages/v1beta1/accesspackageresourcepackageassociation
  labels:
    testing.upbound.io/example-name: accesspackagecatalog
  name: resourcepackageassociation-catalog
spec:
  forProvider:
    displayName: example-catalog
    description: Example access package catalog

---

apiVersion: accesspackages.azuread.upbound.io/v1beta1
kind: AccessPackageResourceCatalogAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: accesspackages/v1beta1/accesspackageresourcepackageassociation
  labels:
    testing.upbound.io/example-name: accesspackageresourcecatalogassociation
  name: resourcepackageassociation-catalogassoc
spec:
  forProvider:
    catalogIdSelector:
      matchLabels:
        testing.upbound.io/example-name: accesspackagecatalog
    resourceOriginId: 00000000-0000-0000-0000-000000000000
    resourceOriginSystem: AadGroup
