# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: serviceprincipaldelegated.azuread.upbound.io/v1beta1
kind: PermissionGrant
metadata:
  annotations:
    meta.upbound.io/example-id: serviceprincipaldelegated/v1beta1/permissiongrant
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    servicePrincipalObjectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    resourceServicePrincipalObjectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: msgraph
    claimValues:
        # These claim match the permission names in the requiredResourceAccess of the Application resource below.
      - openid
      - User.Read
---
apiVersion: serviceprincipals.azuread.upbound.io/v1beta1
kind: Principal
metadata:
  annotations:
    meta.upbound.io/example-id: serviceprincipaldelegated/v1beta1/permissiongrant
    uptest.upbound.io/pre-delete-hook: ../testhooks/delete-permissiongrant.sh
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clientIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
---
apiVersion: applications.azuread.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: serviceprincipaldelegated/v1beta1/permissiongrant
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: example
    requiredResourceAccess:
        # # I got this id from "data.azuread_application_published_app_ids.well_known.result.MicrosoftGraph"
      - resourceAppId: 00000003-0000-0000-c000-000000000000
        resourceAccess:
            # Id obtained from status.atProvider.oauth2PermissionScopeIds["openid"] from the Principal(msgraph) resource below.
          - id: 37f7f235-527c-4136-accd-4a02d197296e
            type: Scope
            # Id obtained from status.atProvider.oauth2PermissionScopeIds["User.Read"] from the Principal(msgraph) resource below.
          - id: e1fe6dd8-ba31-4d61-89e7-88639da4683d
            type: Scope
---
apiVersion: serviceprincipals.azuread.upbound.io/v1beta1
kind: Principal
metadata:
  annotations:
    meta.upbound.io/example-id: serviceprincipaldelegated/v1beta1/permissiongrant
    uptest.upbound.io/pre-delete-hook: ../testhooks/delete-permissiongrant.sh
  labels:
    testing.upbound.io/example-name: msgraph
  name: msgraph
spec:
  forProvider:
    # # I got this id from "data.azuread_application_published_app_ids.well_known.result.MicrosoftGraph"
    applicationId: 00000003-0000-0000-c000-000000000000
    useExisting: true
