# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

name: Tag

on:
  workflow_dispatch: 
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
      message:
        description: 'Tag message'
        required: true

jobs:
  tag:
    uses: upbound/uptest/.github/workflows/provider-tag.yml@standard-runners
    with:
      version: ${{ github.event.inputs.version }}
      message: ${{ github.event.inputs.message }}
