apiVersion: directoryroles.azuread.upbound.io/v1beta1
kind: RoleEligibilityScheduleRequest
metadata:
  annotations:
    meta.upbound.io/example-id: directoryroles/v1beta1/roleeligibilityschedulerequest
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    directoryScopeId: /
    justification: Example
    principalId: ${data.azuread_user.example.object_id}
    roleDefinitionIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: directoryroles.azuread.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: directoryroles/v1beta1/roleeligibilityschedulerequest
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: Application Administrator
